create table if not exists public.photos (
  id bigint generated by default as identity primary key,
  original_name text not null,
  file_path text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.analyses (
  id bigint generated by default as identity primary key,
  photo_id bigint not null references public.photos(id) on delete cascade,
  scene_type text not null,
  mood_category text not null,
  short_review text not null,
  long_review text not null,
  recommended_text_position text not null,
  wallpaper_score integer not null,
  social_score integer not null,
  commercial_score integer not null,
  phrases_json jsonb not null default '[]'::jsonb,
  captions_json jsonb not null default '[]'::jsonb,
  hashtags_json jsonb not null default '[]'::jsonb,
  generation_source text not null default 'mock',
  generation_warning text null,
  content_set_json jsonb null,
  commerce_content_json jsonb null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_photos_created_at
  on public.photos (created_at desc);

create index if not exists idx_analyses_photo_id
  on public.analyses (photo_id);

create index if not exists idx_analyses_created_at
  on public.analyses (created_at desc);

create index if not exists idx_analyses_generation_source
  on public.analyses (generation_source);

create index if not exists idx_analyses_phrases_json_gin
  on public.analyses
  using gin (phrases_json);

create index if not exists idx_analyses_captions_json_gin
  on public.analyses
  using gin (captions_json);

create index if not exists idx_analyses_hashtags_json_gin
  on public.analyses
  using gin (hashtags_json);
